# DO NOT CHANGE, this value is used for internal plugin use only
Version: ${version}
# #################################################################### #
#                                                                      #
#                              Config.yml                              #
#                                                                      #
# #################################################################### #

# Enable debug mode
# Enabling this may result in your console being spammed with message about the plugin
# Only enable this if you want to learn more about the plugin, or are told to by support staff
Debug Mode: false # Defaults to false

# Set this to true if you want to use placeholderAPI in the plugin
PAPI hook: true

# Set PAPI hook to true to use all the placeholderAPI placeholders
# in the messages

# These are the placeholders provided by the plugin
Placeholders:
  Prefix: "&aTardisDev &8|"
  Error: "&cError &8|"
  Success: "&aSuccess &8|"
  Plugin Name: "&bHoverStats"
  Command Name: "HoverStats"
  Placeholder Filler: "0" # Set the default placeholder for any placeholders that are empty or equal "null"

# #################################################################### #
#                         List of placeholders                         #
# #################################################################### #
#                                                                      #
#                    Prefix       -       %prefix%                     #
#                     Error       -       %error%                      #
#                   Success       -       %success%                    #
#               Plugin Name       -       %pluginname%                 #
#              Command Name       -       %cmdName%                    #
#                    Player       -       %player%                     #
#                                                                      #
#                                                                      #
#                           * Disclaimer *                             #
#                  Player may not work for certain                     #
#                              messages                                #
#                                                                      #
# #################################################################### #

# Set the priority at which the chat event will run. Setting this can fix
# Compatibility issues with other plugins
#
# Note: You can find a list of event priorities at the link below:
# https://bukkit.fandom.com/wiki/Event_API_Reference#Event_Priorities
#
# Note: After changing this value, the server must be reloaded/restarted
Chat Event Priority: HIGH # Defaults to HIGH
Join Event Priority: HIGH # Defaults to HIGH
Quit Event Priority: HIGH # Defaults to HIGH

# Set all the different hex patterns you want to support in your chat
#
# Note: By default there is already one hex pattern that the plugin knows
# that hex pattern is the standard (#ffffff) pattern. No need to add that one
# to the list.
#
# Disclaimer: The hex patterns are checked sequentially meaning that the hex
# pattern that is on the top is checked first, then the next pattern and so
# on and so forth. If a hex code isn't working for whatever reason, try to add
# it to the top of the list and try again
Hex Patterns:
  # The default names for each of the hex codes is purely for aesthetics
  "<#ffffff>": # Set a unique name for the hex code
    Prefix: "<#" # Set what prefix the plugin should look for
    Suffix: ">" # Set the suffix that the plugin should look for

  "&#ffffff":
    Prefix: "&#"
    Suffix: ""

# Set the global date format
Date Format: "MM/dd/yy hh:mm:ss"

Chat Formatting:
  # Setting this to false will make it so that another plugin will take control
  # of the chat. Setting this to true will use the formatting below
  Use Formatting: true
  # Set the format of the in game chat
  #
  # Note: You must include "%message%" at some point in your message format.
  # Failure to do so will result in the plugin setting use formatting to false
  # Color is gotten from the final part of the format for the chat. So please
  # ensure that there is nothing after "%message%" that has a different color.
  # Anything that is put after the "%message%" will also be put before the
  # actual message in game.
  Format: "#e8e9eb%displayname% &8&l> &7%message%"


# #################################################################### #
#                                                                      #
#                               Messages                               #
#                                                                      #
# #################################################################### #
Messages:
  System Messages:
    Success:
      PAPI Hook: "&aFound PlaceholderAPI, hooking into it."
      Reloaded: "%success% %pluginname%'s &7config has successfully reloaded!"

    Error:
      PAPI Hook: "&cCouldn't find PlaceholderAPI, any placeholders from PAPI will no longer work."
      No Permissions: "%error% &7You don't have permission to run this command!"

  # Default help message, you can change this if you want
  Help:
    - ""
    - "&7&l&m⎯⎯⎯⎯⎯⎯&r &a&l%pluginname% Help &r&7&l&m⎯⎯⎯⎯⎯⎯&r"
    - "&a/%cmdName% &7- Shows this message."
    - "&a/%cmdName% help &7- Shows this message."
    - "&a/%cmdName% reload &7- Reload's %pluginname%'s config."
    - "&7&l&m⎯⎯⎯⎯⎯⎯&r &a&l%pluginname% Help &r&7&l&m⎯⎯⎯⎯⎯⎯&r"
    - ""

# #################################################################### #
#                                                                      #
#                           Hover Messages                             #
#                                                                      #
# #################################################################### #
Hover:
  First Join:
    - "&7Welcome &b%displayname% &7to the server!"
    - "&7We hope you enjoy your stay!"
    - ""
    - "&e&lClick this to say \"Welcome to the Server!\""
  First Join Click Command: "Welcome to the Server!"

  Join:
    - "&7Welcome back &b%displayname%&7!"
    - ""
    - "&e&lLast Online:"
    - "#556DC8%last_joined%"
    - ""
    - "&e&lClick this to say \"Welcome back\""
  Join Click Command: "Welcome back!"

  Quit:
    - "&e&l%player%'s Stats:"
    - ""
    - "&e&lJoin Date:"
    - "#556DC8%first_joined%"
    - ""
    - "&e&lClick this to message player"
  Quit Click Command: "/mail %player% "

  Stats:
    - "&e&l%player%'s Stats:"
    - ""
    - "&e&lJoin Date:"
    - "#556DC8%first_joined%"
    - ""
    - "&e&lClick this to message player"
  Stats Click Command: "/msg %player% "